name: IDEA-Glue-Blog
version: 0.1.0

author: "Ivan Smolyakov"
maintainer: "self@renesat.me"
copyright: "2020-2023 Ivan Smolyakov"
license: MIT

ghc-options: -Wall

dependencies:
  - base
  - filepath

executables:
  site:
    source-dirs:
      - src
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - base == 4.*
      - hakyll == 4.16.*
      - hakyll-sass == 0.2.4
      - text == 2.*
      - language-javascript == 0.7.*
      - blaze-html (>=0.5 && <0.10)
      - ini
      - unordered-containers
      - process
      - containers
      - aeson
      - bytestring
      - pandoc
      - pandoc-types
      - text-conversions
