resolver: lts-18.13
# resolver: nightly-2021-03-21
packages:
  - .
extra-deps:
  - hakyll-4.15.0.1
  - hakyll-sass-0.2.4

#allow-newer: true
nix:
  enable: true
  shell-file: shell.nix
  add-gc-roots: true
